FROM postgres:12.14-alpine

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432

ENV POSTGRES_USER=${POSTGRES_USER}
ENV POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

VOLUME /var/lib/postgresql/data

CMD ["postgres"]