version: '3.7'

services:
  # financeiro:
  #   container_name: financeiro
  #   restart: on-failure
  #   build: .
  #   volumes:
  #     - .:/app
  #   ports:
  #     - ${PORT}:${PORT}
  #   command: yarn start:dev
  #   env_file:
  #     - .env
  #   depends_on:
  #     - financeiro-db
  postgres:
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    build:
      context: .
      dockerfile: ./Dockerfile.pg
    restart: always    

networks:
  financeiro:


volumes:
  postgres-data:
