name: Tests
on:
  push:
    branches:
      - master

jobs:
  start-postgres:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.pg
          tags: pg-image:latest
          outputs: type=docker,dest=/tmp/pg-image.tar
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: pg-image
          path: /tmp/pg-image.tar

  test:
    needs: start-postgres
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.10.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: pg-image
          path: /tmp
      - name: Load Docker image
        run: |
          docker load --input /tmp/pg-image.tar
          docker run -e POSTGRES_PASSWORD=postgres -p 5432:5432 -d pg-image 
    
      - name: Install dependencies
        run: yarn install --ignore-engines
      - name: Run teste unitario
        run: yarn test:cov
      - name: Run teste e2e
        run: yarn test:e2e
        env:
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
          DATABASE_SYNCHRONIZE: false
          DATABASE_LOGGING: false
          API_NAME: financeiro 
          TZ: UTC
          SECRET_JWT: JwtKey
          NODE_ENV: test
          VERSION: 1.0.0 
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        

